#!/usr/bin/env bash
# appsec-compose — pin scanner images by digest.
#
# Resolves each scanner's pinned tag (from scan-config.yml versions) to its
# immutable repo@sha256:... digest and records them in image-digests.lock.
# Commit the lock for reproducible, tamper-evident scans: render-env.py then
# uses the digests instead of the mutable tags. Re-run after bumping a version.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Refresh .env so *_TAGREF reflect the current scan-config.yml versions.
python3 scripts/render-env.py >/dev/null
set -a; . ./.env; set +a

# ASS_TAGREFS is the space-separated list of every scanner's repo:tag.
read -r -a tagrefs <<< "$ASS_TAGREFS"

{
  echo "# appsec-compose image digests — generated by ./pin.sh. Commit this file."
  echo "# <repo:tag> <repo@sha256:...>"
} > image-digests.lock

for ref in "${tagrefs[@]}"; do
  echo "==> $ref"
  docker pull -q "$ref" >/dev/null
  digest="$(docker inspect --format '{{ index .RepoDigests 0 }}' "$ref")"
  if [[ -z "$digest" ]]; then
    echo "    ! no RepoDigest for $ref (skipped)" >&2
    continue
  fi
  echo "$ref $digest" >> image-digests.lock
  echo "    $digest"
done

# Re-render so .env *_IMAGE now point at the digests.
python3 scripts/render-env.py >/dev/null
echo
echo "Pinned $(grep -c '^[^#]' image-digests.lock) image(s) -> image-digests.lock"
